### ISSUE TITLE
Bug: switch

### ISSUE THREAD

**Issue by ops244** [hass-agent/HASS.Agent#48]
hi, is there any way to make it turn off in the switch mode and not turn on? (the slider in the enabled mode shows that it is turned off and the voice assistant thinks that it is turned off and does not turn off the computer, but turns it on and off at the command)

here are 2 computers in the picture: one is on, the other is off, and the voice assistant thinks that both are off and the slider shows that both are off

![2024-02-16_16-58-19](https://github.com/hass-agent/HASS.Agent/assets/19797600/5358c9b2-7b0c-473e-8ead-609658e9ac2c)

**Comment by amadeo-alex** [comment]
Hello, the bug template is there to make it for us to understand the issue - I can't fully grasp what is the issue here.
The screenshot that you've provided shows two entities, one available and turned off and second unavailable.

Please provide full explanation on what commands are shown on the screen, what would you like to achieve and why you can't do it now.

**Comment by ops244** [comment]
in the screenshot, pc1 is available, but it is displayed as turned off (the slider is turned off), you need it to be turned on

**Comment by amadeo-alex** [comment]
Again, it's hard to understand without a context, what kind of command/entity is the "pc1" and "pc2"?
I can take an educated guess that it might be the "Shutdown" command - if it is, it's not going to work how you'd like it to, it doesn't represent the "state" of PC but rather only allows you to turn it off.

**Comment by ops244** [comment]
yes, you need to display the status, is there no way to do it? these buttons turn out to be useless for voice assistants
