### ISSUE TITLE
Feature:  MultipleKeysCommand/Text with Argument from HA

### ISSUE THREAD

**Issue by Presswerk65** [hass-agent/HASS.Agent#97]
I use hass-agent to do all kind of key commands and enter predefined texts e.g. to password fields where using the clipboard from the PC is prohibited. For that, I have a tablet on my desk and a dashboard with a lot of buttons.

Instead of storing every single KeyCommand on the PC as separate command, it would be nice when I could pass the argument from ha to hass agent (so a service on HA could get the data from an encrypted database and therefor the key is not stored in clear text)

Maybe a service call like
action:
  - service: notify.hass_agent_test_device
    data:
      message: "[T][e][s][t]"
      command: "MultipleKeys"

or

action:
  - service: notify.hass_agent_test_device
    data:
      message: "Test"
      command: "SendText"

**Comment by amadeo-alex** [comment]
Hm, first thing that comes to my mind is Key/MultipleKeys commands accepting action input - for some reason both of those do not support it since the original.
The only concern with this would be the security but on the other hand HASS.Agent can do more "harmful" this if misused than faking the key press.

I'll take a look.
